version: '{build}'
image: Visual Studio 2017

branches:
  only:
  - master
  - develop

pull_requests:
  do_not_increment_build_number: true

before_build:
- nuget restore Sprache.sln
#- choco install xunit
- choco install opencover.portable
- choco install codecov

build_script:
- ps: .\build\build.ps1

#configuration: Release
#build:
#  project: Sprache.sln
#  parallel: true
#  verbosity: minimal

after_build:
- dotnet pack src/Sprache/Sprache.csproj

#test_script:
#- ps: .\build\test.ps1

test_script:
#- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\test\Sprache.Tests\Sprache.Tests.csproj" -filter:"+[*]*" -output:".\Sprache_coverage.xml"
#- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\samples\TinyTemplates.Tests\TinyTemplates.Tests.csproj" -filter:"+[*]*" -output:".\TinyTemplates_coverage.xml"
- OpenCover.Console.exe -register:user -target:"xunit.console.exe" -targetargs:".\test\Sprache.Tests\bin\Debug\net461\Sprache.Tests.dll" -filter:"+[*]*" -output:".\Sprache_coverage.xml"
- OpenCover.Console.exe -register:user -target:"xunit.console.exe" -targetargs:".\samples\TinyTemplates.Tests\bin\Debug\net461\TinyTemplates.Tests.dll" -filter:"+[*]*" -output:".\TinyTemplates_coverage.xml"
- codecov -f "Sprache_coverage.xml"
- codecov -f "TinyTemplates_coverage.xml"

artifacts:
- path: '**\*.nupkg'

#deploy:
#- provider: NuGet
#  api_key:
#    secure: 6xI1jxoZzJ4pIWm4bIufAwdJGy467P+VdIll3/dAAGEpxgISXMIGwMWa77VT3yM9 
#  skip_symbols: true
#  artifact: /.*\.nupkg/
#  on:
#      branch: /^(master|develop)$/
